#!/bin/sh

case "$1" in
    purge)
        rm -rf /var/log/[[service.name]]

        deluser [[service.user]] || true
        delgroup [[service.group]] || true
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
